### ISSUE TITLE
body command not found

### ISSUE THREAD

**Issue by psteinb** [NERSC/slurm-helpers#7]
I saw that you use the `body` command [here](https://doc.zih.tu-dresden.de/hpc-wiki/bin/view/Compendium/JupyterHub) It appears to me that this is NERSC specific, isn't it?

**Comment by sleak-lbl** [comment]
oops - actually it's Steve-specific, it's a shortcut for "run a command, but not on the heading line" .. I've just added it to `functions.sh`

**Comment by psteinb** [comment]
thanks for the quick fix.
